#---------------------------------------------------#
## 更新：2021-12-30 08:24:21
#---------------------------------------------------#
# 外层路由 9870->7890
mixed-port: 7890
port: 7891
socks-port: 7892
redir-port: 7893
allow-lan: true
mode: rule
log-level: silent
bind-address: '0.0.0.0'
external-controller: '0.0.0.0:9090'
secret: '849421294'

